#!/bin/python3

import json,datetime
from subprocess import Popen,PIPE,DEVNULL

icon = { "CHARGING": "▲", "DISCHARGING": "▼", "FULL": "◈" }

def get_battery():
    with Popen("termux-battery-status", stdout=PIPE) as p:
        json_data = p.communicate()[0]
        return json.loads(json_data)

def setroot(text):
    Popen(["xsetroot", "-name", text], stdout=DEVNULL, stderr=DEVNULL)

def main():
    b = get_battery()
    t = datetime.datetime.now()

    setroot("%d:%.2d %d/%d [%d%%%s]" % (t.hour,t.minute,t.month,t.day,b['percentage'],icon[b['status']]))

main()
